// src/data/superChessData.ts
//
// Single source of truth for shared game data: card definitions, engine
// constants (piece values, piece-square tables), and high-level rules.
//
// The canonical file is `src/data/super-chess.json` — a tiny Vite plugin in
// `vite.config.ts` also serves it at `/super-chess.json` (dev) and copies it
// into `dist/` at build time, so the Roblox port can fetch it via HttpService
// and stay in lock-step with the web project without a manual port.
//
// If you need to change card text, rarities, piece values, or constants:
// edit `src/data/super-chess.json`. Both TS and Luau consumers read from there
// (the Luau side gets its embedded snapshot regenerated by `pnpm cards:sync`).
import data from './super-chess.json';
import type { CardDefinition } from '../cards/types.ts';
import type { PieceType } from '../engine/types.ts';

export interface SuperChessData {
  version: string;
  engine: {
    pieceValues: Record<PieceType, number>;
    pieceSquareTables: Record<PieceType, number[]>;
    tempoCompensationCp: number;
    cardEval: {
      frozenPenalty: number;
      shieldBonus: number;
      foulSquarePenalty: number;
    };
  };
  rules: {
    maxHandSize: number;
    maxMovesPerGame: number;
  };
  cards: CardDefinition[];
}

// Cast the JSON to our typed shape. We can't make TS literally infer the
// CardDefinition union from the JSON because `targetType`/`category`/`rarity`
// would widen to `string`, but the data file is hand-edited and validated by
// the unit tests in `tests/data/superChessData.test.ts`.
const RAW_DATA: SuperChessData = data as unknown as SuperChessData;

/** Cards that are "defensive" \u2014 their effect protects you or restricts the
 * opponent and is intended to take effect AFTER your chess move (set up
 * state for the next exchange). The play-phase model lets these be played
 * post-move; offensive / move-modifier cards remain pre-move.
 *
 * Keeping this list local (instead of a JSON tag) means it's easy to grep
 * and changes are an explicit code review, not a silent data tweak. */
const DEFENSIVE_CARDS: ReadonlySet<string> = new Set(['Shield', 'Freeze', 'Foul Ground']);

/** Derive the play phase for a card from its existing metadata + the
 * defensive list. Used when the JSON omits `phase` (forward-compat with
 * legacy data files / the Luau snapshot pre-sync). Order matters:
 *   1. consumesTurn cards are always 'instead' \u2014 the card IS the move.
 *   2. Otherwise, defensive-list members are 'post'.
 *   3. Everything else defaults to 'pre'. */
function derivePhase(card: CardDefinition): 'pre' | 'instead' | 'post' {
  if (card.consumesTurn) return 'instead';
  if (DEFENSIVE_CARDS.has(card.name)) return 'post';
  return 'pre';
}

const ENRICHED_CARDS: CardDefinition[] = RAW_DATA.cards.map((c) => ({
  ...c,
  phase: c.phase ?? derivePhase(c),
}));

export const SUPER_CHESS_DATA: SuperChessData = { ...RAW_DATA, cards: ENRICHED_CARDS };

// Re-exports for convenience (and so consumers don't have to dig through the
// nested object every time).
export const CARD_DEFINITIONS: CardDefinition[] = SUPER_CHESS_DATA.cards;
export const PIECE_VALUES: Record<PieceType, number> = SUPER_CHESS_DATA.engine.pieceValues;
export const PIECE_SQUARE_TABLES: Record<PieceType, number[]> =
  SUPER_CHESS_DATA.engine.pieceSquareTables;
export const TEMPO_COMPENSATION_CP: number = SUPER_CHESS_DATA.engine.tempoCompensationCp;
export const FROZEN_PENALTY: number = SUPER_CHESS_DATA.engine.cardEval.frozenPenalty;
export const SHIELD_BONUS: number = SUPER_CHESS_DATA.engine.cardEval.shieldBonus;
export const FOUL_SQ_PENALTY: number = SUPER_CHESS_DATA.engine.cardEval.foulSquarePenalty;
export const MAX_HAND_SIZE: number = SUPER_CHESS_DATA.rules.maxHandSize;
export const MAX_MOVES_PER_GAME: number = SUPER_CHESS_DATA.rules.maxMovesPerGame;
